version: 0.1
phases:
  build:
    commands:
      - npm install -g @angular/cli && npm install && ng build --target=production
artifacts:
  files:
    - dist/*
    - awsscripts/install_dependencies.sh
    - awsscripts/start_application.sh
    - awsscripts/stop_application.sh
    - awsscripts/aws_codedeploy_config.sh
    - appspec.yml
discard-paths: yes
